---
driver:
  name: ec2
  require_chef_omnibus: 12.17.44
  aws_ssh_key_id: aws_dev
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids:
    - ci-testing
  instance_type: c3.large
  interface: public
  iam_profile_name: prod-singularity-executor

transport:
  name: sftp

provisioner:
  name: chef_zero
  config_rb:
    environment: dev

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[singularity_executor::default]
      - recipe[singularity_executor::s3uploader]
    attributes:
      singularity_executor:
        extra_args:
          - -Xmx192M
          - -test
